use_frameworks!

platform :ios, '8.0'

target 'HHPlaceholderView_Example' do
  pod 'HHPlaceholderView', :path => '../'

  target 'HHPlaceholderView_Tests' do
    inherit! :search_paths

    
  end
end
